name: contexts-example
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -   name: Welcome Message
            env:
                JOB_CONTEXT: ${{ toJson(job) }}
            run: | 
                echo "Welcome to GitHub Actions"
                echo $JOB_CONTEXT


        -   name: Checkout Repo
            uses: actions/checkout@main

        -   name: Run following commands
            env: 
                RUNNER_CONTEXT: ${{ toJson(runner) }}
            run: |
                ls -lstra
                cat README.md
                git --version
                echo $RUNNER_CONTEXT
    deploy:
        if: github.ref == 'refs/heads/feature'
        runs-on: ubuntu-latest
        steps:
        -   name: Testing
            run: echo "This is deployment job" 

