name: second-workflow
on: push
jobs:
    second-job:
        runs-on: ubuntu-latest
        steps:
        -   name: Welcome Message
            run: echo "Welcome"
        
        -   name: Run script
            run: |
                ./print-num.sh
