name: First-Example

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Code
            uses: actions/checkout@main
        -   name: Welcome Message
            run: | 
                echo "My first messgae"
                ls
                cat README.md 
             