name: First-Example

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -   name: Welcome Message
            run: echo "My first messgae"
        -   name: Checkout Code
            uses: actions/checkout@main
        -   name: List Files
            run: ls
        -   name: Read File
            run: cat README.md 
             