name: first-workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -   name: Welcome Message
            run: echo "Welcome to GitHub Actions"

        -   name: Checkout Repo
            uses: actions/checkout@main

        -   name: Run following commands
            run: |
                ls -lstra
                cat README.md
                git --version

