name: first-workflow
on: push

jobs:
    forst-job:
        runs-on: ubuntu-latest
        steps:
        -   name: welcome message
            run: echo "Welcome to CI/CD"
        -   name: Clone repo
            uses: actions/checkout@main
        -   name: Run below commands
            run: |
                ls -a
                date
                git --version



             