name: matrix
on: push
jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                image: [hellow-wold, alpine]
                exclude:
                    -   image: alpine
                        os: windows-latest     
            fail-fast: false
            max-parallel: 2
        runs-on: ${{ matrix.os }}
        steps:
        -   name: Running on ${{ matrix.os}}
            run: echo "Running image ${{ matrix.image }}"

        -   name: Docker run
            run: echo docker run ${{ matrix.image }}